[package]
name = "counting_contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "2.0.3"
serde = { version = "1.0.202", features = ["derive"] }

[dev-dependencies]
cw-multi-test = "2.0.1"
